  target_list:
    - Full_load
    - Incremental_append
    - Incremental_upsert

  Full_load:
    table_name:
      - test_db.transactions
      - test_db.customers
      - test_db.campaigns
      

  Incremental_append:
    table_name:
      - test_db.transactions
      - test_db.customers
      - test_db.campaigns

    loadingQuery: >
      SELECT * FROM transactions
          WHERE date = (SELECT MAX(date) FROM transactions)
      SELECT * FROM customers
                WHERE date = (SELECT MAX(date) FROM customers)
      SELECT * FROM campaigns
                WHERE date = (SELECT MAX(date) FROM campaigns)
      

  Incremental_upsert:
    table_name:
      - test_db.transactions
      - test_db.customers
      - test_db.campaigns
